### ISSUE TITLE
Where is the all caffe python API introduction?

### ISSUE THREAD

**Issue by liulei2140** [nitnelave/pycaffe_tutorial#1]
Hi, sorry to bother you. Where is the all caffe python API introduction? e.g. caffe.SGDSolver(XXXX).  I can't find the API introduction on the internet, and just found some examples from http://nbviewer.jupyter.org/github/BVLC/caffe/blob/master/examples/00-classification.ipynb.

**Comment by nitnelave** [comment]
Hello,

As mentioned in
https://groups.google.com/forum/m/#!topic/caffe-users/MEd2vkXsJRA there is
no python reference. This is the reason why I made this tutorial (even
though it's still far from a reference).
The best way to find what's available is to look at the code: python,
protobuf, and c++.

You can also file a bug against caffe to ask them to publish documentation
(and you should do that), but I wouldn't count on quick results.

Good luck!
