### ISSUE TITLE
which version caffe are you used?

### ISSUE THREAD

**Issue by noticeable** [nitnelave/pycaffe_tutorial#3]
hello
      thanks for your tutorial,i'm going to run your tutorial in my computer.however,there is error in caffe.Net(network_path,caffe_TEST),maybe it's version error with you.may you please tell me which version of caffe you used?

**Comment by nitnelave** [comment]
Hi!

I haven't used Caffe in almost 3 years, so I guess that would be the version from then. Sorry I can't help more, I don't remember the precise version. I guess the tutorial is still mostly relevant, but there may be some minor syntactic differences.

I you find differences, feel free to contribute the corrections!

**Comment by noticeable** [comment]
ok,I see ,thanks for your share and reply
